It appears that the --rc option for autotest isn't working properly, and is resulting in a NoMethodError (because the initializer is expecting an Array, but is getting a String when the -r/--rc option is used when invoking the autotest executable).
The following stacktrace illustrates the issue:

    ~ $ autotest --rc autotest.rc
    /Users/pvandenb/.rvm/gems/ruby-1.9.2-p180/gems/ZenTest-4.5.0/lib/autotest.rb:310:in `initialize': undefined method `each' for "autotest.rc":String (NoMethodError)
        from /Users/pvandenb/.rvm/gems/ruby-1.9.2-p180/gems/ZenTest-4.5.0/lib/autotest.rb:241:in `new'
        from /Users/pvandenb/.rvm/gems/ruby-1.9.2-p180/gems/ZenTest-4.5.0/lib/autotest.rb:241:in `run'
        from /Users/pvandenb/.rvm/gems/ruby-1.9.2-p180/gems/ZenTest-4.5.0/bin/autotest:6:in `<top (required)>'
        from /Users/pvandenb/.rvm/gems/ruby-1.9.2-p180/bin/autotest:19:in `load'
        from /Users/pvandenb/.rvm/gems/ruby-1.9.2-p180/bin/autotest:19:in `<main>'